default:
  address: https://test-stand.gb.ru
  browser: chrome
  sleep_time: 4
  username: "Nastya379"
  password: "2d94b3b2a2"

title_name: Hello
description_name: world
content_name: Hello world!

your_name: Anastasiia
your_email: 89773259782@mail.ru
your_content: Hello world!

url_login: https://test-stand.gb.ru/gateway/login
url_posts: https://test-stand.gb.ru/api/posts
